### ISSUE TITLE
last version Vqmod exhaust the memory and gives PHP fatal Error in OC 3.0.2.0

### ISSUE THREAD

**Issue by Schwannn** [vqmod/vqmod#128] opened 2017-11-06 17:59 UTC
I am runnig 3.0.2.0 clean install and installed the lasted Vqmod Version: 2.6.3
after a few hours of running it produces the following error in log and makes the website show the 500 error.
PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4194304 bytes) in /home/account/public_html/vqmod/vqmod.php on line 341

Even if I increase the memory limit it will still gives the same error.
Everything will be back to normal if I replace the entire Vqmod directory with a fresh install Vqmod.

**Comment by qphoria** [comment] 2017-11-06 21:03
That's literally just a text file. Hard to think that could be getting too big. Also double check that your attempts to increase the memory are actually taking effect with the phpinfo check. Sometimes hosts ignore the memory increase.

**Comment by Schwannn** [comment] 2017-11-07 21:25
I did check the memory size and it was increased, no matter what size it is increased to, it gets exhausted. But the memory increase should not be necessary for a file like this, I disabled the function related to line 341 and it is working fine since then. I am thinking maybe that function is not compatible with 3.0.2.0

**Comment by Schwannn** [comment] 2017-11-08 01:59
This is the part of the code that is making the issue wth OC 3.0.2.0
`
	/**
	 * VQMod::_loadChecked()
	 *
	 * @return null
	 * @description Loads already checked files and adds them to _doNotMod array
	 */
	private static function _loadChecked() {
		$file = self::path(self::$checkedCache);
		if($file && is_file($file)) {
			$paths = file($file, FILE_IGNORE_NEW_LINES | FILE_SKIP_EMPTY_LINES);
			if(!empty($paths)) {
				foreach($paths as $path) {
					$fullPath = self::path($path, true);
					if($fullPath) {
						self::$_doNotMod[] = $fullPath;
					}
				}
			}
		}
	}`

**Comment by Schwannn** [comment] 2017-11-08 02:10
I just checked the log file again and this is what I found 

`[07-Nov-2017 22:32:29 UTC] PHP Fatal error:  Uncaught exception 'Twig_Error_Loader' with message 'Unable to find template "mail/order.twig" (looked into: /home/domain/storage/modification/catalog/view/theme, /home/domain/public_html/catalog/view/theme).' in /home/domain/public_html/vqmod/vqcache/vq2-system_library_template_Twig_Loader_Filesystem.php:215
Stack trace:
#0 /home/domain/public_html/vqmod/vqcache/vq2-system_library_template_Twig_Loader_Filesystem.php(139): Twig_Loader_Filesystem->findTemplate('mail/order.twig')
#1 /home/domain/public_html/system/library/template/Twig/Environment.php(312): Twig_Loader_Filesystem->getCacheKey('mail/order.twig')
#2 /home/domain/public_html/system/library/template/Twig/Environment.php(378): Twig_Environment->getTemplateClass('mail/order.twig', NULL)
#3 /home/domain/public_html/vqmod/vqcache/vq2-_home_schwann_storage_modification_system_library_template_twig.php(51): Twig_Environment->loadTemplate('mail/order.twig')
#4 /home/domain/storage/modification/system/library/template.php(63): Template\Twig->render in /home/domain/public_html/vqmod/vqcache/vq2-system_library_template_Twig_Loader_Filesystem.php on line 215
[08-Nov-2017 00:01:20 UTC] PHP Fatal error:  Allowed memory size of 134217728 bytes exhausted (tried to allocate 4194304 bytes) in /home/domain/public_html/vqmod/vqmod.php on line 341`

**Comment by Schwannn** [comment] 2017-11-13 04:55
Even after adding 512M to memory and a very light opencart I still get the flowing `Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 16777216 bytes) in /home/domain/public_html/vqmod/vqmod.php on line 341` 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by qphoria** [comment] 2017-11-13 20:18
I just don't know why. I cannot reproduce that at all and haven't heard or seen any other servers with the issue. It could be that even though you are changing the php.ini to change the memory, your host isn't allowing it. Perhaps phpinfo might show the actual allowed memory.

**Comment by JAY6390** [comment] 2017-11-13 20:25
I seem to have a vague recollection of this from a while back. It was due to the paths not being correct and the checked.cache file getting out of control because the paths were never matching. What sort of size is the checked.cache file in the /vqmod/ directory, and can you put it on pastebin (edit out any sensitive data first) and post the link

**Comment by twdre** [comment] 2018-01-04 11:01
Same problem here. 
Giving the same memory errors. 
Also increased memory size.
And also the site gives me a blank page, front end backend.

**Comment by siteadvicenl** [comment] 2018-01-25 13:45
Any status on this issue? It seems to be a combination of VQMOD 2.6.3 and Opencart 3.0.2.0 and clients are annoyed that their website keeps going offline.

**Comment by JAY6390** [comment] 2018-01-25 13:48
Can't replicate this at all personally. @siteadvicenl what size was your checked.cache file? And does it have duplicate entries in it?

**Comment by siteadvicenl** [comment] 2018-01-25 13:55
I'll have to wait until it happens again and give full details.

The client website goes down about every 6 days, with the error message "Allowed memory size of *** bytes exhausted". I raised the memory size which only resulted longer wait until the site goes down.

**Comment by JAY6390** [comment] 2018-01-25 13:56
If it's what I think it is, it'll already be happening after a few page reloads. Probably better to check the file while it's smaller tbh

**Comment by siteadvicenl** [comment] 2018-01-25 14:03
Definitely not happening after a few page-reloads and website has a decent daily traffic.

Current checked.cache: https://pastebin.com/MvJEfj3Z (219k), every reload increases the size.

**Comment by JAY6390** [comment] 2018-01-25 14:09
@siteadvicenl Well it is what I was expecting. Notice the paths are full in most instances. That shouldn't be the case ever. If I recall correctly, this was happening because of path aliases on a site I worked on and fixed.

**Comment by siteadvicenl** [comment] 2018-01-25 14:13
That would than exactly point the problem. Opencart 3.0.2.0 expects the "/storage/" to be outside the public_html. If not, the admin will be given an alert with every login.

All the files that are "full" are files in the storage. 
Can you give me an advice regarding those path aliases?

**Comment by JAY6390** [comment] 2018-01-25 14:18
Ah you're absolutely right @siteadvicenl . The only way would be to ignore the paths outside the vqmod directory from being added to checked.cache, or to move the storage directory back into the OC directory and just use .htaccess to block any access. For now, a simple solution to your issue would be to run a cron job daily at say 3am when the site traffic is quietest to just truncate the checked.cache file until we can implement some sort of fix for this

**Comment by siteadvicenl** [comment] 2018-01-25 22:14
Appreciating the support.
Cron is a good Idea to keep the file in proportion and not reaching memory-limits.
Will also try to see how opencart reacts on having the storage directory in the OC directory and possibly disable the alert in the admin.

Hope to see a newer version of VQMod soon.

**Comment by karthickkg** [comment] 2018-02-04 21:16
Hope the below information is of some help to resolve this issue as I am having the same issue too on OC3.0.2. 
Had it in OC2.0 as well. I resolved it by commenting out the below code in system/startup.php.
```
if (is_file(DIR_STORAGE . 'vendor/autoload.php')) {
	require_once(DIR_STORAGE . 'vendor/autoload.php');
}
```
I used to get loads of "/home/user/storage/vendor/autoload.php" entry in checked.cache file and commenting out the above resolved the issue. This fix was based on discussions at https://github.com/vqmod/vqmod/issues/94

Have moved to OC 3.0.2 recently and having the same issue again. But this time I am getting multiple entries of all the lines that start with "/home/user/storage/modification/". Not sure which lines add this in the checked.cache file. Remember reading some discussions in the forums stating that this issue is something to do with the file paths defined in the index.php files. 

Having profiled the website, the above issue adds about 1 second of processing time over a day. every entry is being checked by the _loadChecked() function.

**Comment by karthickkg** [comment] 2018-02-04 21:38
Just wanted to add that any file with full path gets added multiple times. But file names without full path has only one entry.

**Comment by nichinu** [comment] 2018-02-09 10:24
I am having the exact same issue on OC 3.0.2.0 that @karthickkg mentioned.....

**Comment by x3seriesx** [comment] 2018-02-12 07:54
The problem is that OC 3.0.2.0 isn't compatible with PHP Version 7.1 so if you have that (check on cPanel), then downgrade to 7.0 instead. Also, don't forget to bump up the memory limit back to 512M because changing the PHP version reverts the memory limit back to default at 128M. This seemed to work for me after I refreshed my site 4-5 times. Good luck guys.

**Comment by karthickkg** [comment] 2018-02-17 15:15
@x3seriesx have changed the php version to 7.0, 5.6 and 5.4 and am still getting the issue. Any file which starts with "catalog/.." or "system/.." does not seem to repeat. Any filename that startes with "/home/..." gets listed each and every time.

Surprised that only few people have this issue.

**Comment by JAY6390** [comment] 2018-03-04 00:24
Sorry for the delay... fairly simple fix for this. See issue #135

**Closed by JAY6390** 2018-03-04 00:24 UTC

**Comment by frantoqui** [comment] 2018-04-19 06:47
@JAY6390 is right, the only way to fix it for now is running truncate -s 0 /var/www/html/opencart/vqmod/checked.cache when it happens. Hope they fix this bug soon.

**Comment by bluethumb** [comment] 2018-09-28 12:03
I have the /opencart/vqmod/checked.cache in sub dir of (http)root and have the same problem @Schwannn . As I read it here the solution is a cron job to set the opencart/vqmod/checked.cache to 0 byte ? Or wait till an update of vqmod . By the way vpmod.php state it is ver. 2.6.2 ?

**Comment by qphoria** [comment] 2018-09-28 15:49
There is not much we can do from the vQmod side. It's a file security limitation of having files in a directory above vQmod. Perhaps if we also moved the vQmod class up a level but that will take further thought. 

Ultimately, OpenCart's decision to move downloads, uploads, and logs up a level is good security practice, if a bit overkill...  but it should not be including the modification folder. Unfortunately it's all lumped together in the storage folder. You could get creative and move only the modification folder straight into the system folder and leave the rest of the storage folder outside of the root directory. Then update the config.php files to change the DIR_MODIFICATION path to DIR_SYSTEM . 'modifications'

For now, karthickkg's post [above](https://github.com/vqmod/vqmod/issues/128#issuecomment-362940322) is the simplest solution.

**Comment by kombi77** [comment] 2018-12-06 17:38
Thanks for all the information this issue been plaguing since we moved to 3.0.x .  Is there fix yet that does not involve changing the way OC is currently designed?

**Comment by kombi77** [comment] 2018-12-06 19:35
Update - I tried to update the config.php files  changing it DIR_MODIFICATION path to DIR_SYSTEM .  After moving the folder as suggested.  It broke some extensions and our Journal 3 theme. I did flush cache in VQmod, theme, and OC.

**Comment by qphoria** [comment] 2018-12-06 19:44
You need to click the refresh button on the Extensions -> Modifications page in the admin after moving. Also be sure you've updated the config.php and admin/config.php

**Comment by kombi77** [comment] 2018-12-06 21:09
Thanks for the reply.  I did do both of them.  The issues I saw was with the Journal3 theme and the SEO extension. I will spin up a test site to see if I can gather more information.

**Comment by kombi77** [comment] 2018-12-06 22:36
I see what I did wrong I did not follow the path in the config.php which shows clearly the DIR_SYSTEM path is the system folder in OC.  I placed the "modification" folder I moved directly under public_html the first time. 

define('DIR_SYSTEM', '/home/siteuser/public_html/system/');
define('DIR_MODIFICATION', DIR_SYSTEM . 'modification/');

**Comment by kombi77** [comment] 2018-12-06 23:16
After the change the VQmod checked.cache is now logging lots of storage/vendor/autoload.php entries.  

/home/username/ocdata/storage/vendor/autoload.php
/home/username/ocdata/storage/vendor/autoload.php
/home/username/ocdata/storage/vendor/autoload.php
/home/username/ocdata/storage/vendor/autoload.php
