### ISSUE TITLE
cache fail

### ISSUE THREAD

**Issue by billynoah** [vqmod/vqmod#46] opened 2015-06-30 21:32 UTC
There seems to be an intermittent problem with the two cache files not staying in sync:
- vqmod/checked.cache
- vqmod/mods.cache

It happens sometimes if you update an xml file and the cache doesn't catch it for some reason and you end up with corrupted, partially modded or sometimes duplicated mods in the vqcache.  Workaround is either resave xml (sometimes needs to be resaved 3 or 4 times before vqcached file is rendered correctly) or delete everything in the `vqcache` folder along with the two files mentioned above after revisions are made. This happens particularly often with servers I work on that have high traffic and many vqmods.  Setting `$_devMode` to true helps but comes with it's own set of issues.

Are you aware of a setting configuration to eliminate the possibility of this happening?  A real fix would be much appreciated.

**Comment by billynoah** [comment] 2016-03-04 14:53
Really?  That's awesome news... would you mind elaborating a wee bit on the solution?

**Comment by JAY6390** [comment] 2016-03-04 14:55
Hi Billy

I've closed the issue as I've not been able to replicate the issue in all the time that this ticket has been opened, and not had any other feedback from others on the ticket that anyone else has had the problem. Are you still getting the same thing?

Kind regards
Jay

**Comment by billynoah** [comment] 2016-03-04 15:58
yes, it's ongoing and i can replicate it on over 5 different sites.  the affected sites are getting a high rate of traffic and typically have 50+ vqmods.  it's something i've been meaning to dig into myself but it should not be closed. unless you changed something in the caching methods in this latest release.

**Comment by billynoah** [comment] 2016-03-04 16:00
if you want to get in touch i can help try to reproduce this for you  - or I will work on it myself when time allows

**Comment by JAY6390** [comment] 2016-03-04 16:00
Hi Billy

OK, I'll re-open it for you. Nothing has been changed in regards to this on the latest version. Can you provide more info on your server, php version etc etc - the more the better

Kind regards
Jay

**Comment by billynoah** [comment] 2016-03-04 16:05
I've seen this happen with more than one configuration but typically I am running  Ubuntu 14.04.3 on a reasonably well resourced VPS (8gb, 6cores, SSD) - and I keep things up to date.  Currently PHP 5.5.9-1ubuntu4.14.  As I said, it mostly happens when many vqmods are installed and when server is getting hit hard with requests at the same moment a vqmod is getting updated / saved.  On a website with high traffic this is nearly always.

**Comment by trueliarx** [comment] 2017-06-14 12:42
I've the same problem right now and I tried to check the "issues" if there are fixes.
Sometimes vqcache files are not generated.

One of the problems, but It needs to be verified better, could be that the xml files are not utf-8 (no bom) and there's no <?xml version="1.0" encoding="UTF-8"?> (probably not really needed ... but I added it anyway).

Usually I have no problems withhout them but few minutes ago I encountered it and it PROBABLY (I'm not 100% sure) got fixed by converting the xml file to utf-8 without bom.

Note again that I'm not 100% sure but for the last 10 minutest that's what worked in my specific case.

**Closed** 2017-07-17 17:56 UTC

**Comment by billynoah** [comment] 2017-07-17 20:18
Why is this being closed?  Was it fixed post 2.6.1?

**Comment by MarcPinnell** [comment] 2018-09-18 23:02
I've just come across this looking for a solution to this problem. May not be the same exact problem but I have a couple of OC sites with vqmod exhibiting random corrupt vqcache files (resulting in a 500 error). When they become corrupt, deleting the contents of the cache folder brings the site back. We are currently running a cron file to test the site every 5 minutes and if error delete the files. Not the best solution of course. Today I ran into a problem where one of the admin files was corrupt so the head didn't load, but the rest of the page loaded (resulting in no css or js).
Running OC 3.02 on Cloud Linux, PHP 7.X.

**Comment by JAY6390** [comment] 2018-09-19 10:10
@MarcPinnell When you are testing, are you able to determine exactly which files are corrupted? If you are, you could simply delete the corrupt cache file which should still bring the site back without possibly corrupting the other files. Still not able to reproduce this issue myself at all

**Comment by MarcPinnell** [comment] 2018-09-20 17:16
So it happened again this morning. Attached is a zip file that contains copies of the vqmod folder. One while the site was producing the 500 error and one copy of the folder after I cleared the vqmod cache and hit a couple pages on the site so it would rebuild the cache. Hope it helps.

Marc





====================
Marc Pinnell
Director of Web Services
marcp@shasta.com
www.shasta.com
833 Mistletoe Lane, Suite A1
Redding, CA 96002
530-224-6866 Ext. 100
