### ISSUE TITLE
Template files are not modified in OpenCart 2.2.0.0a

### ISSUE THREAD

**Issue by bull5-i** [vqmod/vqmod#71] opened 2016-01-27 18:28 UTC
It seems, that vQmod 2.5.1 for OpenCart does not fully work with the OpenCart 2.2.0.0 alpha release.
Modifications to template files are not applied.

**Comment by JAY6390** [comment] 2016-01-27 18:34
I don't doubt it but until there is a definitive version it's not worth looking into it to be honest - just in case they change it all up again before release which happens quite a lot

**Comment by siriusdev** [comment] 2016-03-02 16:42
vqmod_opencart.xml file for OC 2.2.0.0
`<?xml version="1.0" encoding="UTF-8"?>
<modification>
	<id>VQMOD CORE FOR OPENCART - DO NOT REMOVE</id>
	<version>1.4.x and above</version>
	<vqmver required="true">2.5.2</vqmver>
	<author>vqmod.com</author>
	
	<file name="system/startup.php,system/engine/*.php,system/library/*.php,admin/controller/extension/*.php,system/library/template/*.php">
		<operation error="skip" info="For non OCMod includes/requires">
			<search position="replace" regex="true"><![CDATA[~(require|include)(_once)?\((?!modification\()([^)]+)~]]></search>
			<add><![CDATA[$1$2(\\VQMod::modCheck($3)]]></add>
		</operation>
		<operation error="skip" info="For OCMod includes/requires - OPERATION MUST BE AFTER NON OCMOD INCLUDES/REQUIRES OPERATION">
			<search position="replace" regex="true"><![CDATA[~(require|include)(_once)?\(modification\(([^)]+)~]]></search>
			<add><![CDATA[$1$2(\\VQMod::modCheck(modification($3), $3]]></add>
		</operation>
	</file>

</modification>`

**Comment by nikto1** [comment] 2016-03-02 17:52
@siriusdev : great thanks :+1:

**Comment by JAY6390** [comment] 2016-03-02 18:03
@siriusdev Is that all that's required for it to work on 2..2.x ?

**Comment by siriusdev** [comment] 2016-03-02 18:49
Yes, as far as I can see, it seems only tpl files were not VQMODed in 2.2, this modification adds tpl support on the new template engine.
Quickly tested my mods and all seems to be working fine.

**Comment by imakeitwork** [comment] 2016-03-04 09:09
Will there be a new version of vQmod to fully support the 2.2.0.0? The posted workaround is great but for extension customers this will be a serious issue, and I don't think it's right to add this code to the vqmod extensions itself... Thanks!

**Comment by siriusdev** [comment] 2016-03-04 10:06
[http://www.opencart.com/index.php?route=extension/extension/info&extension_id=22378](http://www.opencart.com/index.php?route=extension/extension/info&extension_id=22378)

This is a install package I made for installing vqmod directly through extension installer, it is the official version (no weird implementation of vqmod), and the fix for 2.2.0.0 is included.
There is no problem to put this code in the extension itself (I copied here the whole xml file but really only a few things have changed), I think it will be included in official version soon or later.

**Comment by imakeitwork** [comment] 2016-03-04 10:09
Thanks, never noticed this extension before!

**Comment by bull5-i** [comment] 2016-03-04 10:34
Will there be an actual release in this repo as well?

**Comment by JAY6390** [comment] 2016-03-04 12:20
Hi

Yes we will be releasing a new version in the next couple of days. Any client stores shouldn't be running the bleeding edge version of OC right now anyway, and we're looking at getting OCMods to run through VQMod itself at the same time as releasing this so that OCMods can be uploaded just like XMLs are

Kind regards
Jay

**Comment by delveswood** [comment] 2016-03-04 12:25
@siriusdev @JAY6390 In OC2.2 there's a new file: system/framework.php
Does this need including in the file name attribute, along side system.startup.php? i.e.
`<file name="system/framework.php,system/startup.php,system/engine/*.php,system/library/*.php,admin/controller/extension/*.php,system/library/template/*.php">`

**Comment by JAY6390** [comment] 2016-03-04 12:27
Most probably yes @delveswood. I've not actually taken a look at 2.2 just yet

**Comment by siriusdev** [comment] 2016-03-04 15:43
@delveswood: There is nothing in framework.php that needs to be binded to vqmod, all require/include are in other files so it is not necessary to include it in the paths at this time.

**Comment by qphoria** [comment] 2016-03-04 19:47
@siriusdev if you would be so kind as to update your file with the latest 2.6.0 changes. This has support for adding attritbutes in the <add> tag and fix for some garbage theme that replaces the ocmod core files causing vqmod's to double modify. It also includes your changes for 2.2.x. I hate to have multiple unaligned versions out there.

**Comment by siriusdev** [comment] 2016-03-04 20:52
That's great! Already experienced this double modify but didn't find the cause.
I have updated the package.
Thanks.

**Comment by JAY6390** [comment] 2016-03-04 20:56
@siriusdev it appears to be Journal2 that does it. It modifies the `install.php` and `modification.php` in `/admin/controller/extension/` and you'll see two backup files in there with a `.original` added to their names. Restoring those fixes the issue and I've not seen anything affected in the theme by it either. Why themes feel the need to do that I don't know. They're getting bigger than the store they're running on at this rate

**Comment by iReptile** [comment] 2016-03-05 15:45
Can it be that the ignoreif attribute doesn't work anymore in 2.6.0?

Just tested my extensions with the above code and they wherw fine.
Now deleted vqmod and installed the 2.6.0 and it seems like ignoreif doesn't work anymore.

**Comment by qphoria** [comment] 2016-03-05 22:12
Just found a bug in 2.6.0 that prevented it working on windows servers.
I've patched and released 2.6.1
@Siriusdev please update your script.

@iReptile
I just tested ignoreif and found it to be working normally.

Cheers,

Tom "Qphoria"
OpenCartGuru.com

**Comment by haxcop** [comment] 2016-03-05 22:45
HI, 
This is will work to any previous OCV-2X ? or just for 2.2.0.a?.
I’m Using 2..3..1 with journal2

**Comment by qphoria** [comment] 2016-03-05 23:33
The latest vQmod is currently backwards compatible as far back as OpenCart
1.4.x

Cheers,

Tom "Qphoria"
OpenCartGuru.com

**Comment by haxcop** [comment] 2016-03-05 23:39
Thanks!

**Comment by iReptile** [comment] 2016-03-06 12:37
@qphoria

Then please tell me why my ignore if attribute does work on 2.1.0.2 with vqmod 2.5.1 but does not work on 2.2.0.0 with vqmod 2.6.1?

I changed absolutely nothing on the ignore if code in my extension.
Just tested on a fresh install 2.2.0.0 with vqmod 2.6.1

Tested the same 2 extension which both make use of the same newly created tab but only add the tab if it does not already exists. (by using the ignoreif attribute)

But in 2.2.0.0 I get the same tab created double. Whilst in 2.1.0.2 it only creates 1 tab.

**Comment by qphoria** [comment] 2016-03-06 15:41
@iReptile 
I'm not sure why it isn't working for you. I just tested it again and created a test script. I tested it with 2.5.1 and 2.6.1 and in both cases the ignoreif worked fine. I've attached the script here.
[vqmod_ignoreif_test.zip](https://github.com/vqmod/vqmod/files/160389/vqmod_ignoreif_test.zip)

See if that works for you. If ignoreif is working then you should only see the message once.

**Comment by iReptile** [comment] 2016-03-06 18:47
@qphoria 

Thanks but I solved the problem.
Somehow you have changed somthing so my old code does not work as before.

I used to enter it like this:

`<ignoreif><![CDATA[
        my code
        ]]></ignoreif>`

It always worked as I said.

But with vqmod 2.6.1 I have to change it to:

`<ignoreif><![CDATA[my code]]></ignoreif>`

It has to be 1 line now to work as before I could use 3 lines for easy viewing.
Don't understand why but I will change the code in my extentions.

**Comment by qphoria** [comment] 2016-03-06 19:03
@iReptile 
Yes you are right.. I made a small change to the ignoreif to change it from a VQSearchNode to just VQNode.. vQSearchNode has trim=true by default
VQNode has trim=false by default
My mistake.
I'd hate to release yet another version though now that 2.6.1 is out

**Comment by iReptile** [comment] 2016-03-06 20:58
Ok no problem.
I'll just change this in my extentions that use ignoreif.
But I thought maybe I was doing something wrong but it is clear now.

**Closed** 2016-03-10 12:33 UTC

**Comment by sindhu10** [comment] 2016-04-13 05:00
Hi, i am using opencart 2.2.0 and i have installed vqmod from above mentioned link.
http://www.opencart.com/index.php?route=extension/extension/info&extension_id=22378

Everything is fine, but i am unable to add any content in any of the template files.
ex: i need to add one menu link in header.tpl. But it is not displaying. I have refreshed extensions->modifications in admin also.

Please can any one help me.. Thank you :)

**Comment by sindhu10** [comment] 2016-04-13 05:02
HI, I am asking about the front end tpl files. I am using basic default template.

Please tel me what i have to change??

**Comment by JAY6390** [comment] 2016-04-13 21:36
@sindhu10 - Install the latest version (2.6.0) from this site - We don't have any support for third party integrations, especially those that could be outdated

**Comment by qphoria** [comment] 2016-04-14 17:27
FYI the latest version is 2.6.1, not 2.6.0.

Q

**Comment by jks0586** [comment] 2017-04-13 17:23
This is very use full link for the new version of vqmod.

**Comment by jks0586** [comment] 2017-04-13 17:23
New version of vqmod not support for template(.tpl) files modification or overwriting. So many thanks for this

**Comment by qphoria** [comment] 2017-04-13 17:54
There is no issue with vQmod and template files. Check your scripts.

**Comment by jks0586** [comment] 2017-04-14 00:38
Previously My vqmod_opencart.xml have this code 
<file path="system/" name="startup.php,engine/*.php,library/*.php">
		<operation error="skip">
			<search position="replace" regex="true"><![CDATA[~(require|include)(_once)?\(([^)]+)~]]></search>
			<add><![CDATA[$1$2(VQMod::modCheck($3)]]></add>
		</operation>
	</file>

but unfortunately it was not working for the  tpl file overwriting.

But when I us this code in vqmod_opencart.xml like this

<file name="system/startup.php,system/engine/*.php,system/library/*.php,admin/controller/extension/*.php,system/library/template/*.php">
        <operation error="skip" info="For non OCMod includes/requires">
            <search position="replace" regex="true"><![CDATA[~(require|include)(_once)?\((?!modification\()([^)]+)~]]></search>
            <add><![CDATA[$1$2(\\VQMod::modCheck($3)]]></add>
        </operation>
        <operation error="skip" info="For OCMod includes/requires - OPERATION MUST BE AFTER NON OCMOD INCLUDES/REQUIRES OPERATION">
            <search position="replace" regex="true"><![CDATA[~(require|include)(_once)?\(modification\(([^)]+)~]]></search>
            <add><![CDATA[$1$2(\\VQMod::modCheck(modification($3), $3]]></add>
        </operation>
    </file>


Then It work for me to overwrite the tpl file.
So if you have any idea that my original vqmod_opencart.xml can overwrite the .tpl file.
Please let me know.

I was using this code to overwriting the tpl file i.e.

<file name="admin/view/template/catalog/product_form.tpl">
    <operation error="skip">
      <search position="before" index="2"><![CDATA[<div class="form-group required">]]></search>
      <add><![CDATA[
        <div class="form-group">
          <label class="col-sm-2 control-label" for="input-short-description<?php echo $language['language_id']; ?>"><?php echo $entry_short_description; ?></label>
          <div class="col-sm-10">
            <textarea name="product_description[<?php echo $language['language_id']; ?>][short_description]" placeholder="<?php echo $entry_short_description; ?>" id="input-short-description<?php echo $language['language_id']; ?>" class="form-control <?php echo $short_description_summernote;?>"><?php echo isset($product_description[$language['language_id']]) ? $product_description[$language['language_id']]['short_description'] : ''; ?></textarea>
          </div>
        </div>
        ]]></add>
    </operation>
  </file>

Many Thanks
